version: '3'

services:
  database:
    image: postgres:14-alpine
    container_name: db
    platform: linux/amd64 # for platform error on Apple M1 chips
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

volumes:
  strapi-data:
